# Project information
site_name: EZCast Pro Dokumentation
site_url: 'https://doc.ezcastpro.de'
site_author: 'STÜBER SYSTEMS GmbH'
site_description: >-
    Unsere Dokumentation für alle EZCast Pro Produkte. 

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/stuebersystems/doc.ezcastpro.de'

# Copyright
copyright: '&copy; 2022 STÜBER SYSTEMS GmbH'

# Configuration
theme:
    name: material
    custom_dir: overrides
    static_templates:
        - 404.html
    include_search_page: false
    search_index_only: true
    language: de
    features:
        - navigation.tabs
        - navigation.instant
    palette:
        scheme: default
    favicon: assets/img/favicon.ico
    logo: assets/img/logo.svg
    font: false

# Legal links
extra:
    legal:
        - label: Impressum
          link: https://www.stueber.de/imprint.php
        - label: Datenschutz
          link: https://legal.stueber.de/privacy.php

# Customization
extra_css:
    - assets/css/custom.css

# Plugins
plugins:
    - search
    - minify:
        minify_html: true

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.abbr
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde  

# Page tree
nav:
- Überblick: 
    - Einführung: index.md
    - Was ist neu?: whatsnew.md
    - Anschlüsse: ports.md
    - CMS (Central Management System): cms.md
    - Datensicherheit: datasecurity.md
    - Firmware aktualisieren: firmware-upgrade.md
- Pro Stick II: 
    - Überblick: pro-stick-d10/intro.md
    - Schnellstartanleitung: pro-stick-d10/quickstart.md
    - Was ist neu?: pro-stick-d10/whatsnew.md
    - Anleitungen nach<br>Betriebssystem: 
        - "Anleitung: Android": pro-stick-d10/quickstart/#android-und-ios
        - "Anleitung: iOS": pro-stick-d10/quickstart/#android-und-ios
        - "Anleitung: macOS": pro-stick-d10/quickstart/#windows-und-macos
        - "Anleitung: Linux": pro-stick-d10/linux.md
        - "Anleitung: Windows": pro-stick-d10/quickstart/#windows-und-macos
    - Anleitungen nach<br>Streamingprotokoll: 
        - "Anleitung: AirPlay": pro-stick-d10/airplay.md
        - "Anleitung: Google Cast": pro-stick-d10/googlecast.md
        - "Anleitung: Miracast": pro-stick-d10/miracast.md
    - CMS (Central Management System): pro-stick-d10/cms.md    
    - Einrichtungshinweise: pro-stick-d10/setup-tipps.md  
    - Erweiterte Funktionen:
        - Captive Portal: pro-stick-d10/captiveportal.md
        - Dynamisches Hintergrundbild: pro-stick-d10/dynamicwallpaper.md
        - Erweiterte Einstellungen: pro-stick-d10/adv.settings.md
        - Festgelegter Host: pro-stick-d10/fixedhost.md
        - Monitor-Modus: pro-stick-d10/monitor-setup.md
        - ProCast: pro-stick-d10/procast.md
        - Sicherheitscodes: pro-stick-d10/securitycodes.md
        - Unbeaufsichtigte Installation: pro-stick-d10/proapp-silentinstall.md
    - EZCastPro App/Software: pro-stick-d10/ezcastproapp.md     
    - Firmware aktualisieren: pro-stick-d10/firmware-upgrade.md
    - Internetzugang: pro-stick-d10/internet.md
    - Problembehandlung:  
        - DxDiag-Bericht erstellen: pro-stick-d10/dxdiag.md    
        - Einstellungen zurücksetzen: pro-stick-d10/reset.md
        - Firmware neu installieren: pro-stick-d10/firmware-reinstall.md
        - Mit Hotspot verbinden: pro-stick-d10/hotspot.md
        - Leistungstest durchführen: pro-stick-d10/performancetest.md
        - Logdatei herunterladen: pro-stick-d10/logfile.md
        - Projizieren auf diesen PC: pro-stick-d10/project2PC.md
- Pro Box II: 
    - Überblick: pro-box-b10/intro.md
    - Schnellstartanleitung: pro-box-b10/quickstart.md
    - Was ist neu?: pro-box-b10/whatsnew.md
    - Anleitungen nach<br>Betriebssystem: 
        - "Anleitung: Android": pro-box-b10/quickstart/#android-und-ios
        - "Anleitung: iOS": pro-box-b10/quickstart/#android-und-ios
        - "Anleitung: macOS": pro-box-b10/quickstart/#windows-und-macos
        - "Anleitung: Linux": pro-box-b10/linux.md
        - "Anleitung: Windows": pro-box-b10/quickstart/#windows-und-macos
    - Anleitungen nach<br>Streamingprotokoll: 
        - "Anleitung: AirPlay": pro-box-b10/airplay.md
        - "Anleitung: Google Cast": pro-box-b10/googlecast.md
        - "Anleitung: Miracast": pro-box-b10/miracast.md
    - CMS (Central Management System): pro-box-b10/cms.md        
    - Einrichtungshinweise: pro-box-b10/setup-tipps.md  
    - Erweiterte Funktionen:
        - Captive Portal: pro-box-b10/captiveportal.md
        - Dynamisches Hintergrundbild: pro-box-b10/dynamicwallpaper.md
        - Erweiterte Einstellungen: pro-box-b10/adv.settings.md
        - Festgelegter Host: pro-box-b10/fixedhost.md
        - Monitor-Modus: pro-box-b10/monitor-setup.md
        - ProCast: pro-box-b10/procast.md
        - Sicherheitscodes: pro-box-b10/securitycodes.md
        - Touch-Back-Funktion: pro-box-b10/touchback.md
        - Unbeaufsichtigte Installation: pro-box-b10/proapp-silentinstall.md
    - EZCastPro App/Software: pro-box-b10/ezcastproapp.md        
    - Firmware aktualisieren: pro-box-b10/firmware-upgrade.md
    - Internetzugang: pro-box-b10/internet.md
    - Problembehandlung: 
        - DxDiag-Bericht erstellen: pro-box-b10/dxdiag.md  
        - Einstellungen zurücksetzen: pro-box-b10/reset.md
        - Firmware neu installieren: pro-box-b10/firmware-reinstall.md  
        - Leistungstest durchführen: pro-box-b10/performancetest.md
        - Logdatei herunterladen: pro-box-b10/logfile.md
        - Projizieren auf diesen PC: pro-box-b10/project2PC.md 
- CMS: 
    - Einführung: cms.md
- Ältere Modelle: 
    - Einführung: legacymodels.md
    - Pro Stick I: 
        - Überblick: pro-stick-d01/intro.md
        - Schnellstartanleitung: pro-stick-d01/quickstart.md
        - "Anleitung: AirPlay": pro-stick-d01/airplay.md
        - "Anleitung: Miracast": pro-stick-d01/miracast.md
        - Erweiterte Einstellungen: pro-stick-d01/adv.settings.md
        - Einstellungen zurücksetzen: pro-stick-d01/reset.md
        - Internetzugang: pro-stick-d01/internet.md
    - Pro LAN Box: 
        - Überblick: lan-box-b01/intro.md
        - Schnellstartanleitung: lan-box-b01/quickstart.md
        - "Anleitung: AirPlay": lan-box-b01/airplay.md
        - "Anleitung: Miracast": lan-box-b01/miracast.md
        - Erweiterte Einstellungen: lan-box-b01/adv.settings.md
        - Einstellungen zurücksetzen: lan-box-b01/reset.md
        - Internetzugang: lan-box-b01/internet.md
