#Workflow to mirror this repo to Azur DevOps

name: Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-18.04
    steps:                                             
    - uses: actions/checkout@v1
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          https://stuebersystems@dev.azure.com/stuebersystems/wireless%20presentation/_git/doc.ezcastpro.de
        ssh_private_key:
          ${{ secrets.AZUREDEVOPSSSHPRIVATEKEY }}
